name: codenames
description: "Codenames is a word-based party game where players compete to uncover hidden words and outsmart their opponents. Join the fun and test your wits in this multiplayer game!"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flip_card: ^0.7.0
  numberpicker: ^2.1.2
  socket_io_client: ^2.0.3+1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  confetti: ^0.8.0
  shared_preferences: ^2.3.3
  just_audio: ^0.9.42
  intl: ^0.19.0
  vibration: ^2.0.1
  flutter_styled_toast: ^2.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: null

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    # - .env
