name: codenames
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flip_card: ^0.7.0
  numberpicker: ^2.1.2
  socket_io_client: ^2.0.3+1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner:

flutter:
  uses-material-design: true
